# Creation date : 22.08.2022
# Created by : CSR
# Description : Create two containers (one for the db and the other one of the administration front-end)
#
version: '3.3'

services:
  db:
    image: mysql:8.0.30
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    restart: always
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./scripts:/scripts
  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

# The database will be persistent among containers restarts.
volumes:
  dbdata: