version: '3.0'

networks:
  db_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

services:
  db:
    image: mysql/mysql-server:5.7
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    restart: always
    ports:
      - "3306:3306"  # Port exposé pour se connecter depuis l'hôte
    expose:
      - 3306  # Port exposé pour la communication entre les services Docker
    volumes:
      - "./data.sql:/docker-entrypoint-initdb.d/db_clickGame.sql"
    networks:
      db_network:
        ipv4_address: 192.168.0.10  # Adresse IP statique du conteneur MySQL dans le réseau
